[workspace]
# we release most of the repo as a group so disable things for individual packages
changelog_update = false
git_release_enable = false
git_tag_enable = false

# create the release PR in draft to avoid running CI till we're ready
pr_draft = true

[[package]]
name = "cynic"

git_tag_name = "v{{version}}"
git_tag_enable = true
git_release_enable = true

changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = [
    "cynic-cli",
    "cynic-codegen",
    "cynic-introspection",
    "cynic-proc-macros",
    "cynic-querygen-web"
]

[[package]]
name = "cynic-parser"
git_tag_enable = true
git_release_enable = true
