// These are generated by LARLPOP
#[allow(unused_braces)]
mod executable;
#[allow(unused_braces)]
mod schema;

pub use executable::*;
pub use schema::*;

use crate::{common::MalformedStringError, lexer::LexicalError};

pub enum AdditionalErrors {
    Lexical(LexicalError),
    MalformedString(MalformedStringError),
    MalformedDirectiveLocation(usize, String, usize),
    VariableInConstPosition(usize, String, usize),
}
