[book]
authors = ["Graeme Coupar"]
language = "en"
multilingual = false
src = "src"
title = "Cynic - A GraphQL Client For Rust"

[output.html]
git-repository-url = "https://github.com/obmarg/cynic"

[output.linkcheck]  
# Enable link checking
